CREATE TABLE IF NOT EXISTS players(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(255) NOT NULL UNIQUE,
	score INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS q_and_a(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	question TEXT NOT NULL UNIQUE,
	answers TEXT NOT NULL,
	correct_answers TEXT NOT NULL,
	multi_choice BOOL NOT NULL DEFAULT 0
)